name: list
description: A Dart app that uses Angular 2
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.17
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  http: ^0.11.3+7
  domquery: ^1.1.3
  less_dart: ^0.3.3
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    entry_points:
    - 'web/scripts/list.dart'
- less_dart
- dart_to_js_script_rewriter
